# Generated by Django 2.1.1 on 2018-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_nm', models.CharField(max_length=100, unique=True)),
                ('service_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'company_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryOpiton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_fk', models.IntegerField()),
                ('option_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search_option', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'library_opiton_tb',
                'managed': False,
            },
        ),
    ]
