# Generated by Django 2.2.1 on 2019-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('book_location', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField()),
                ('image_source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'book_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('book_nm', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(max_length=80)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_year', models.TextField()),
            ],
            options={
                'db_table': 'isbn_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nfc',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('shelf_height', models.IntegerField()),
                ('shelf_width', models.IntegerField()),
                ('shelf_location', models.CharField(max_length=100)),
                ('image_source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nfc_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userkey_fk', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('managerkey_fk', models.IntegerField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('answerdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qna_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userkey_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('library', models.IntegerField()),
                ('user_status', models.IntegerField()),
            ],
            options={
                'db_table': 'user_tb',
                'managed': False,
            },
        ),
    ]
